# Generated by Django 2.1.7 on 2020-08-02 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0003_auto_20200802_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=100, null=True)),
                ('published_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_draft', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='static/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.User')),
            ],
        ),
    ]
